---
- name: Install Redsocks
  ansible.builtin.package:
    name:
      - redsocks
    state: present

- name: Configure Redsocks config
  ansible.builtin.template:
    src: redsocks.conf.j2
    dest: /etc/redsocks.conf
    owner: root
    group: adm
    mode: '0640'
  notify: Restart redsocks

- name: Install nftables.
  when:
    - redsocks_firewall == 'nftables'
  ansible.builtin.include_tasks:
    file: nftables.yml

- name: Install iptables.
  when:
    - redsocks_firewall == 'iptables'
  ansible.builtin.include_tasks:
    file: iptables.yml
