---
- name: Install Redsocks and nftables
  ansible.builtin.package:
    name:
      - redsocks
      - nftables
    state: present

- name: Configure Redsocks config
  ansible.builtin.template:
    src: redsocks.conf.j2
    dest: /etc/redsocks.conf
    owner: root
    group: adm
    mode: '0640'
  notify: Restart redsocks

- name: Configure nftables rules
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: adm
    mode: '0640'
  notify: Restart nftables

- name: Enable redsocks service
  ansible.builtin.systemd:
    name: redsocks
    state: started
    enabled: true

- name: Enable nftables service
  ansible.builtin.systemd:
    name: nftables
    state: started
    enabled: true
